name: Dev Pull Request CI
on:
  pull_request:
    types:
      - opened
    branches:
      - dev
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        go: [1.16]
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Build and Test
        run: |
          go build ./...
          go test ./...
